import { Page } from '@playwright/test';

export async function mockBridge(page: Page) {
  await page.addInitScript(() => {
    const api: Record<string, any> = {};

    function auto(name: string, value?: any) {
      api[name] = (...args: any[]) => {
        const result = typeof value === 'function' ? value(...args) : value;
        return result !== undefined ? result : null;
      };
    }

    // All possible bridge methods with sensible defaults
    auto('checkConnection', true);
    auto('getVersion', '0.1.0');
    auto('getPlatform', 'windows');
    auto('getPathSeparator', '\\');
    auto('getConfig', null);
    auto('getAppVersion', { version: '0.1.0', app_name: 'JARVIS' });
    auto('checkForUpdates', { current_version: '0.1.0', latest_version: '', update_available: false, releases: [], error: '' });
    auto('getAvailableVersions', []);
    auto('downloadAndInstall', { success: true, path: 'C:\\Temp\\JARVIS.exe', restart: false });
    auto('quitApp', undefined);
    auto('getModules', []);
    auto('getModule', null);
    auto('listModels', []);
    auto('getModel', null);
    auto('getModelBySpecialty', null);
    auto('pullModel', true);
    auto('deleteModel', true);
    auto('startModel', true);
    auto('stopModel', true);
    auto('updateModelMetadata', true);
    auto('getModelServerStatus', { running: false, command: 'ollama serve', pid: 0, error: '' });
    auto('startModelServer', true);
    auto('getRoots', []);
    auto('listFiles', []);
    auto('getRecentFiles', []);
    auto('readFile', '');
    auto('writeFile', true);
    auto('createFile', true);
    auto('createDirectory', true);
    auto('deletePath', true);
    auto('renamePath', true);
    auto('movePath', true);
    auto('openWorkspace', true);
    auto('addRoot', true);
    auto('removeRoot', true);
    auto('getProjectInfo', null);
    auto('editorOpenFile', null);
    auto('editorSaveFile', true);
    auto('editorCloseFile', true);
    auto('editorGetOpenFiles', []);
    auto('editorDetectLanguage', 'text');
    auto('editorSearchFiles', []);
    auto('editorGetSettings', {});
    auto('editorUpdateSettings', true);
    auto('gitIsRepo', true);
    auto('gitStatus', []);
    auto('gitLog', []);
    auto('gitBranches', []);
    auto('gitCurrentBranch', 'main');
    auto('gitCreateBranch', true);
    auto('gitCheckout', true);
    auto('gitDeleteBranch', true);
    auto('gitCommit', true);
    auto('gitStageAll', true);
    auto('gitStage', true);
    auto('gitUnstage', true);
    auto('gitPull', true);
    auto('gitPush', true);
    auto('gitDiff', '');
    auto('gitDiffGutter', []);
    auto('gitSetCredentials', true);
    auto('listAgents', []);
    auto('getAgent', null);
    auto('createAgent', null);
    auto('updateAgent', true);
    auto('deleteAgent', true);
    auto('setDefaultAgent', true);
    auto('getDefaultAgent', null);
    auto('getOrchestrationPool', []);
    auto('listNotes', []);
    auto('getNote', null);
    auto('createNote', null);
    auto('updateNote', true);
    auto('deleteNote', true);
    auto('searchNotes', []);
    auto('getFolders', []);
    auto('moveNote', true);
    auto('getGraph', { nodes: [], edges: [] });
    auto('getBacklinks', []);
    auto('getOrchestrationConfig', { enabled: true, strategy: 'auto', max_agents_per_query: 3, critic_enabled: true });
    auto('updateOrchestrationConfig', true);
    auto('executeOrchestratedQuery', '');
    auto('getAgentTrace', null);
    auto('sendMessage', 'Hello!');
    auto('cancelGeneration', undefined);
    auto('listChatHistory', []);
    auto('loadChat', []);
    auto('networkGet', { statusCode: 200, body: '{}' });
    auto('networkPost', { statusCode: 200, body: '{}' });
    auto('networkOAuthStart', '');
    auto('networkOAuthComplete', '');
    auto('networkListApiKeys', []);
    auto('networkStoreApiKey', true);
    auto('networkGetApiKey', '');
    auto('networkDeleteApiKey', true);
    auto('networkGetStoredToken', null);
    auto('networkClearToken', true);
    auto('terminalCreate', 'term-1');
    auto('terminalWrite', true);
    auto('terminalResize', true);
    auto('terminalClose', true);
    auto('terminalCloseAll', true);
    auto('terminalList', []);
    auto('mcpListServers', []);
    auto('mcpGetServer', null);
    auto('mcpCreateServer', null);
    auto('mcpUpdateServer', null);
    auto('mcpDeleteServer', true);
    auto('mcpStartServer', true);
    auto('mcpStopServer', true);
    auto('mcpListTools', []);
    auto('mcpCallTool', '');
    auto('workflowList', []);
    auto('workflowGet', null);
    auto('workflowCreate', null);
    auto('workflowUpdate', true);
    auto('workflowDelete', true);
    auto('workflowExecute', null);
    auto('securityGetPermissions', []);
    auto('securitySetPermission', true);
    auto('securityGetAuditLog', []);
    auto('securityListSecrets', []);
    auto('securityGetSecret', '');
    auto('securityStoreSecret', true);
    auto('securityDeleteSecret', true);
    auto('llmGenerate', { content: '', done: true });
    auto('llmGetProviders', []);
    auto('llmGetProvider', null);
    auto('llmSaveProvider', true);
    auto('llmSetDefaultProvider', true);
    auto('llmTestConnection', { success: true, message: 'OK' });
    auto('llmGetDefaultProvider', null);
    auto('showFolderPicker', null);
    auto('copyToClipboard', true);
    auto('revealInExplorer', true);
    auto('getRelativePath', '');
    auto('createFileWithPath', true);
    auto('listDirectory', []);

    window.pywebview = { api };
  });
}
